# languages used in the repository
language: python
python:
  - "3.4"

# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "pip install coveralls"

# scripts to run tests and coverage analyzer
script:
 - coverage run --source=src/manage.py src/user_summary/tests.py
 - flake8 src/

# whitelisting only master branch
branches:
  only:
    - master
    - dev

# to produce coverage analysis
after_success:
  coveralls
